### ISSUE TITLE
Pyments --> Unpaid Plans problem

### ISSUE THREAD

**Issue by Partymann2000** [VertisanPRO/pterodactyl#124]
### Resource

WemX Pro

### Describe the issue

It is not possible to Completen Unpaid Plans manule

### Pterodactyl Panel Version

1.2.0

### Resource Version

1.2.0

### To Reproduce

1. A User buy a server without money 
2.  you go to admin --> payments --> unpaid
3.  select manage in the unpaid plan
4. click complete order  and nothing happened
5.  when u click of invoice you redirtet to the account you have clicked on manage

### Expected Behaviour

-

### Screenshots

https://github.com/VertisanPRO/pterodactyl/assets/53320411/de1b4638-11eb-4934-a458-55a75252ee11

### Additional Information

---

**Comment by Mubeen142** [comment]
Hi @Partymann2000 

Thank you for reporting this bug. The bug has been fixed in the next update:
![image](https://github.com/VertisanPRO/pterodactyl/assets/58806240/8fcd05f8-e3f5-4c97-b451-0101623af749)

You can now complete the payment manually. The system will complete the payment and perform actions for the payment i.e create an order, or extend etc...
