### ISSUE TITLE
Complete Payment not working

### ISSUE THREAD

**Issue by Shockingg** [VertisanPRO/pterodactyl#184]
### Resource

WemX Pro

### Describe the issue

Currently if you have an unpaid invoice, and an admin attempts to complete the payment it simply does not work. Just a bug that needs fixing asap.

### Pterodactyl Panel Version

1.11.3

### Resource Version

1.4.0

### To Reproduce

1. Make an unpayed invoice
2. Try complete it

### Expected Behaviour

Invoice gets marked as paid and the date is extended.

**Comment by VanillaChan6571** [comment]
@Shockingg There is a work around if this is an issue, you can modify the date & invoice in the database of wemx. I recommend using PHPAdmin to apply the extended date or error / issue you have.

**Comment by Shockingg** [comment]
Yes thank you, it is what I'll have to do for now until the issue is fixed.

**Comment by Mubeen142** [comment]
Hi @Shockingg 

Thank you for reporting this bug. The bug has been fixed in the next update:

![image](https://github.com/VertisanPRO/pterodactyl/assets/58806240/7e512b69-ef6c-4489-895b-dc0c96361bc8)

You can now complete the payment manually. The system will complete the payment and perform actions for the payment i.e create an order, or extend etc...
