### ISSUE TITLE
IP Ban problem

### ISSUE THREAD

**Issue by Partymann2000** [VertisanPRO/pterodactyl#190]
### Resource

WemX Pro

### Describe the issue

If I give a user an IP ban, everyone who has given the ip ban also gets an ip ban

### Pterodactyl Panel Version

1.11.3

### Resource Version

1.5.0

### To Reproduce

https://www.youtube.com/watch?v=8yKot4phMqc

**Comment by Mubeen142** [comment]
Hi @Partymann2000 

As we've determined, the issue is not with the ban system but with the IPS that are collected. Panels that are using CloudFlare proxy return inaccurate user IPs as a result when you IP ban someone everyone gets banned,

We are working on a better way to collect the IPs that does not get hindered by CloudFlare
