### ISSUE TITLE
Problem with Exclude checkout variables

### ISSUE THREAD

**Issue by Gh0st-cmd** [VertisanPRO/pterodactyl#223]
### Product

WemX Pro

### Describe the issue

There is a problem with Exclude checkout variables it does not display all the available variables so I cannot hide certain important variables when paying customers

### Pterodactyl Panel Version

1.11.3

### Product Version

1.7.1

### To Reproduce

1. Go to Paquets 2. Select Paquets and edit or create 3. Try to remove a variable

### Expected Behaviour

The expected behavior is that we can hide the desired variables when paying users

### Screenshots

![Capture_decran_2023-10-01_233417](https://github.com/VertisanPRO/pterodactyl/assets/61194866/331d0156-11d1-45ce-8116-beeefa56a770)
![image](https://github.com/VertisanPRO/pterodactyl/assets/61194866/ffa01f09-0cb6-4958-aff8-4283866e0a35)

**Comment by VanillaChan6571** [comment]
_Select variables you do not want users to be able to modify at checkout_

That means by Default QueryPort and BlobSyncPort cannot be edited by the user in general so this cannot be excluded since its already excluded. So I have no idea what the issue is, could you explain more since I do Host SOFT myself.

**Comment by GIGABAIT93** [comment]
just remove this right to change in the pterodactyl panel
![зображення](https://github.com/VertisanPRO/pterodactyl/assets/59637348/49014131-5aac-4b02-bb5d-7cc6c79737ff)
