### ISSUE TITLE
Soft/Hard Update

### ISSUE THREAD

**Issue by starrider346** [VertisanPRO/pterodactyl#243]
### Product

WemX Pro

### Describe the solution you'd like

When updating, you can have the option to perform a soft or hard update. 

Hard update works like how it currently works. 

Soft update will work more like git where it will only modify the areas that have been modified. 

This would be useful for people who have made small tweaks all over the place like tailwind or line spacing. Allow them to transition quicker instead of spending like 3 hours redoing all your changes and instead spend only like 10 mins redoing the changes in just the updated files.

**Comment by Mubeen142** [comment]
Hi @starrider346 

unfortunately its complicated to add such a system. It's not something that we will be adding due to this reason.

We open-sourced our themes, modules and other repos on github. As a developer, you can just make a fork and merge the latest changes as they are vissible in these public repos
