### ISSUE TITLE
Plan Updates Dont Sync

### ISSUE THREAD

**Issue by ZEROPOINTBRUH** [VertisanPRO/pterodactyl#29]
### Resource

Billing

### Describe the issue

When updating the plans. The database syncs with the website on new plans, but active plans dont sync up. 

### Pterodactyl Panel Version

1.11.2

### Resource Version

2.5.5

### To Reproduce

Admin: Updates price/ram/cpu/egg/etc. to plan
Costomer with active plan: Keeps the previous plan and pays the same price as it previously costed.

### Expected Behaviour

Servers should sync up with there active plans.

**Comment by Mubeen142** [comment]
Hi,

There is currently no way of updating server resources because of this exact reason, so I am not sure where you are editing the memory, disk etc for plans unless you are editing through phpmyadmin which is not supported.

As for the price, I just checked and it does update when you update it in the admin area.

**Comment by ZEROPOINTBRUH** [comment]
nono, what i mean is when the costomer buys the server, and the pricing of the plan changes. the price that the costomer use to have will be the price replacing the current one.
