### ISSUE TITLE
Reduce the button sizes for the client panel

### ISSUE THREAD

**Issue by ZEROPOINTBRUH** [VertisanPRO/pterodactyl#30]
### Resource

Billing

### Is your feature request related to a problem? Please describe

ok the only place i'm talking about are the buttons on the left side when you login to the clients panel. They're just way too big and bulky on space. kinds reminds me of the windows 8 start menu.
```
[ Button 1 ] Item
[ Button 1 ]
\ Unnecessary Border
```

### Describe the solution you'd like

I think the buttons just need to be smaller. and remove the Unnecessary border to the button.

Just keep it simple
[○] Item
[□] Item 2

**Comment by AuroraRpg** [comment]
Continuing on with this thread, I'm am going onto a different issue i have with the panel. The lack of a divider between icons that go to the server itself (server owner stuff) and account / admin panel stuff.


**Here's what i mean**

_This is a photo of the changes i made simply within Firefox_
![firefox_EXafDAEH2h](https://user-images.githubusercontent.com/23438816/188256289-c44b13fc-0ca2-4031-ba10-c9b71b567475.png)
There's a divider between the items meant to control the server and the items like account settings and admin items. I Also Re-arranged the order of some items to an order i think makes sense.

_This is what it currently is_
![firefox_Ttx7bfSQ62](https://user-images.githubusercontent.com/23438816/188256341-0c47fd6c-dbb7-480b-931c-d85c80ce3ac0.png)
There is no divider between the two category of icons, both doing very different things. i think it can make the panel more confusing when it comes navigating, especially if you're an admin just simply using the panel.

If this can simply be implemented it would be great.

Cheers!

**Comment by ZEROPOINTBRUH** [comment]
Why can't we get the one shown in this demo here?
![](https://cdn.discordapp.com/attachments/829060225674903603/965265384062193684/consoledark1.png)
![](https://cdn.discordapp.com/attachments/829060225674903603/965265385442127932/logindark1.png)

**Comment by PadowYT2** [comment]
Because that's literally ModernUI and not Carbon

**Comment by AuroraRpg** [comment]
ModernUI seems much more simpler and better than carbon. the smaller widgets make it much better to navigate the pterodactyl panel

Here's what i mean, im simply going to compare  the sidebar

**Carbon:**
![image](https://user-images.githubusercontent.com/23438816/188257691-c7325880-2729-49a4-b7e9-16f2e051e31c.png)
The buttons are way bigger and there so make it so that one has to scroll to reach other buttons

**ModernUI:**
![image](https://user-images.githubusercontent.com/23438816/188257732-87679d29-c9c8-4256-ba20-c7e85fb5b78d.png)
ModernUI has smaller and cleaner looking icons, it makes the user experience overall butter as more can fit on screen. i also think the placement of where the user widget is way better than on carbon. its gives more detail on the user than just a simple icon that just says.

Both themes are really good, but i would go out to suggest that Carbon could be tweaked a bit to make the user experience more enjoyable. Anyways that's just a statement i wanted to put out there

**Comment by MyShoesHaveSplinters** [comment]
I agree, the UI that comes with unix and billing node are way too large, Modern UI would be a great addition to the billing node.
