### ISSUE TITLE
Package ID Dont Show

### ISSUE THREAD

**Issue by TheCiROMG** [VertisanPRO/pterodactyl#443]
### Describe the issue

Basically, that, I have already made several packages and they have their numbers, but magically, in these they disappeared and I don't know how to make them reappear, users can see them and purchase them, but it causes me problems when changing names and characteristics of the same, because I can't find them and I don't have a quick URL to modify them

![opera_R5UTQkrQhk](https://github.com/WemXPro/tracker/assets/61605643/ff290d2b-b379-42db-89f6-7016074b5a2e)

### Product Version

2.0.1

### Pterodactyl Panel Version (if applicable)

1.11.5

**Comment by GIGABAIT93** [comment]
Hello, this is strange, I did not find such a problem. Have you made any changes to the template? Are you using the default template? I think the problem is that id 0 is written statically in the template and I suspect that it happened because you made some changes to the files. Provide more information after your actions this problem occurred
